name: Validate links

on:
  push:
    branches:
      - main
  schedule:
    - cron: 2 * * * *

jobs:
  build:
    name: Validate links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate links
      uses: ad-m/report-link-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
